_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
hidden size:
    value: 64
lr:
    value: 0.8
lstm cells number:
    value: 5
mode:
    value: TrainAndTest
steps:
    value: 20
